openapi: 3.0.0
info:
  title: Medication Reminder API
  description: API for managing medications and reminders for users, caregivers, and children.
  version: "1.0.0"
servers:
  - url: http://localhost:5000
    description: Local server

tags:
  - name: Authentication
    description: Endpoints related to user authentication
  - name: Medications
    description: Endpoints related to managing medications
  - name: Reminders
    description: Endpoints related to managing reminders

paths:

  /login:
    post:
      tags:
        - Authentication
      summary: User login
      requestBody:
        description: Login with username and password
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for authentication
        '401':
          description: Invalid credentials

  /register:
    post:
      tags:
        - Authentication
      summary: User registration
      requestBody:
        description: Register a new user
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
                  enum: [child, user, caregiver]
      responses:
        '201':
          description: User registered successfully
        '409':
          description: User already exists

  /medication/add:
    post:
      tags:
        - Medications
      summary: Add a medication
      requestBody:
        description: Add a new medication for a user
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the medication
                dosage:
                  type: string
                  description: Dosage of the medication
                purpose:
                  type: string
                  description: Purpose of the medication
                side_effects:
                  type: string
                  description: Side effects of the medication
                precautions:
                  type: string
                  description: Precautions for the medication
                warnings:
                  type: string
                  description: Warnings for the medication
                user_id:
                  type: integer
                  description: ID of the user to whom the medication belongs
      responses:
        '201':
          description: Medication added successfully
        '400':
          description: Failed to add medication

  /medication/{med_id}:
    get:
      tags:
        - Medications
      summary: Get medication details
      parameters:
        - name: med_id
          in: path
          required: true
          description: ID of the medication
          schema:
            type: integer
      responses:
        '200':
          description: Medication details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  dosage:
                    type: string
                  purpose:
                    type: string
                  side_effects:
                    type: string
                  precautions:
                    type: string
                  warnings:
                    type: string
        '404':
          description: Medication not found

  /reminder/add:
    post:
      tags:
        - Reminders
      summary: Add a reminder
      requestBody:
        description: Add a reminder for a medication
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                medication_id:
                  type: integer
                  description: ID of the medication
                time_to_take:
                  type: string
                  format: date-time
                  description: Time to take the medication (format: YYYY-MM-DD HH:MM:SS)
      responses:
        '201':
          description: Reminder added successfully
        '400':
          description: Invalid input or failed to add reminder

  /reminders/upcoming:
    get:
      tags:
        - Reminders
      summary: Get upcoming reminders
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of upcoming reminders for the user
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    medication_name:
                      type: string
                    dosage:
                      type: string
                    time_to_take:
                      type: string
                      format: date-time
                    taken:
                      type: boolean
        '404':
          description: No upcoming reminders found
        '401':
          description: Unauthorized (Invalid or missing token)

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Medication:
      type: object
      properties:
        id:
          type: integer
          description: Unique ID of the medication
        name:
          type: string
          description: Name of the medication
        dosage:
          type: string
          description: Dosage of the medication
        purpose:
          type: string
          description: Purpose of the medication
        side_effects:
          type: string
          description: Side effects of the medication
        precautions:
          type: string
          description: Precautions for using the medication
        warnings:
          type: string
          description: Warnings associated with the medication
        user_id:
          type: integer
          description: ID of the user to whom the medication belongs

    Reminder:
      type: object
      properties:
        id:
          type: integer
          description: Unique ID of the reminder
        medication_id:
          type: integer
          description: ID of the associated medication
        time_to_take:
          type: string
          format: date-time
          description: Time when the reminder is scheduled
        taken:
          type: boolean
          description: Whether the medication was taken or not

    User:
      type: object
      properties:
        id:
          type: integer
          description: Unique ID of the user
        username:
          type: string
          description: Username of the user
        role:
          type: string
          description: Role of the user (child, user, caregiver)

security:
  - BearerAuth: []

